## Please do not change this file.
## Doing so will unfortunately create unnesseccary merge conflicts between branches and the fork, and nordugrid/arc version of this file.
## To have the automatic builds work on your fork, check that the runner is enabled in your fork: Settings->CI/CD->Runner settings

stages:
  - deploy_and_test

deploy_staging_deb9:
  stage: deploy_and_test
  image: docker:stable
  script:
    - ls -lhrt /arc-testfiles
    - ls -lhrt /arc-logs
    - name_container=deb9_`date +%Y%m%dT%H%M`
    - docker image rm maikenp/arc-deploy-debian9 || true 
    - docker run --name=$name_container --privileged -v "/arc-testfiles:/arc-testfiles:rw" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-debian9
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - docker stop $name_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - docker-socket-runner1
  allow_failure: true

deploy_staging_el6:
  stage: deploy_and_test
  image: docker:stable
  script:
    - ls -lhrt /arc-testfiles
    - ls -lhrt /arc-logs
    - name_container=el6_`date +%Y%m%dT%H%M`
    - docker image rm maikenp/arc-deploy-centos6 || true 
    - docker run --name=$name_container --privileged -v "/arc-testfiles:/arc-testfiles:rw" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-centos6
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - docker stop $name_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - docker-socket-runner-bgo4 
  allow_failure: true

deploy_staging_centos7:
  stage: deploy_and_test
  image: docker:stable
  script:
    - pwd
    - ls -lhrt
    - ls -lhrt rpmbuild
    - echo $CI_PROJECT_DIR
    - export DOCKER_API_VERSION=1.19
    - gitlab_container=$(docker ps -a | awk 'FNR>1' | awk '{print $NF}')
    - echo $gitlab_container
    - deploy_container=el7_`date +%Y%m%dT%H%M`
    - echo $deploy_container
    - echo "Test" > $CI_PROJECT_DIR/rpmbuild/test.rpm
    - cat $CI_PROJECT_DIR/rpmbuild/test.rpm
    - docker run  --name=$deploy_container  --volumes-from $gitlab_container --privileged -v "/$CI_PROJECT_DIR/rpmbuild:/rpmbuild:rw" -v "/arc-testfiles:/arc-testfiles:rw" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-centos7
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - rm -rf $CI_PROJECT_DIR/rpmbuild
    - docker stop $name_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - 158.39.75.5
  allow_failure: true