## Please do not change this file. 
## Doing so will unfortunately create unnesseccary merge conflicts between branches and the fork, and nordugrid/arc version of this file. 
## To have the automatic builds work on your fork, check that the runner is enabled in your fork: Settings->CI/CD->Runner settings

stages:
  - rpms
  - deploy_test
  
make_rpms:
  stage: rpms
  image: maikenp/centosarc2
  script: 
  - yum update -y
  - ./autogen.sh
  - ./configure
  - yum-builddep -y nordugrid-arc.spec
  - echo "Preparing and running rpmbuild"
  - mkdir -p $CI_PROJECT_DIR/rpmbuild/{SOURCES,BUILD,RPMS,SRPMS}
  - echo "%_topdir $CI_PROJECT_DIR/rpmbuild" > ~/.rpmmacros
  - export VERSION=`cat VERSION`
  - make dist
  - cp "nordugrid-arc-${VERSION}.tar.gz" $CI_PROJECT_DIR/rpmbuild/SOURCES
  - rpmbuild -D "_topdir $CI_PROJECT_DIR/rpmbuild" -ba nordugrid-arc.spec
  - cd $CI_PROJECT_DIR
  tags:
    - general-shared 
  artifacts:
    when: on_success
    paths:
    - $CI_PROJECT_DIR/rpmbuild/SRPMS/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/noarch/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/x86_64/
  allow_failure: false
 
deploy_staging:
  stage: deploy_test
  script:
    - echo "Deploy to staging server"
    - yum install -y time
    - ls -lhrt
    - mkdir allrpms
    - cp rpmbuild/RPMS/noarch/* allrpms
    - cp rpmbuild/RPMS/x86_64/* allrpms
    - cd allrpms
    - yum localinstall *.rpm -y
    - wget http://svn.nordugrid.org/trac/nordugrid/export/32500/contrib/certificate_generator/CertificateGenerator.py
    - python CertificateGenerator.py --CA autocertif --host 158.39.75.5 --validity 365
    - ls -lhrt
    - mv host* /etc/grid-security/
    - mv autocertif* /etc/grid-security/certificates
    - mv *.0 /etc/grid-security/certificates
    - ls -lhrt /etc/rc.d/init.d
    - ls -lhrt /etc/arc.conf
    - /etc/rc.d/init.d/a-rex validate
    - /etc/rc.d/init.d/a-rex start
    #- /etc/rc.d/init.d/gridftpd start
    - echo 'Now run some tests - like submitting jobs'
    - sleep 2m
    - /etc/rc.d/init.d/a-rex stop
    #- /etc/rc.d/init.d/gridftpd stop
    - ls -lhrt /var/www/html/arc-logs
    #- ls -lhrt /var/www/html/arc-tests
    - cp -r /var/www/html/arc-logs $CI_PROJECT_DIR
    #- cp -r /var/www/html/arc-tests $CI_PROJECT_DIR
    - sleep 2m
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     - $CI_PROJECT_DIR/arc-tests/
  dependencies:
    - make_rpms
  tags:
    - deploy
  only: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  allow_failure: true

##for some reason get /var/www/html/arc-tests no such file or directory, while it is created and looks exactly like the /var/www/html/arc-logs folder
##can also downlaod the rpms from latest job with wget 'https://source.coderefinery.org/nordugrid/arc/-/jobs/artifacts/master/download?job=make_rpms' -O artifacts.zip
