#test timestamp
stages:
  - deploy_and_test


deploy_staging_el8:
  stage: deploy_and_test
  image: docker:stable
  script:
    - pwd
    - echo $CI_PROJECT_DIR
    - ls -lhrt
    - ls -lhrt $CI_PROJECT_DIR/rpmbuild/*
    - export DOCKER_API_VERSION=1.19
    - deploy_container=el8_`date +%Y%m%dT%H%M`
    - docker pull maikenp/arc-deploy-centos7
    - gitlab_container=$(docker ps  | awk 'FNR==2' | awk '{print $NF}')
    - cp -r $CI_PROJECT_DIR/rpmbuild/* /rpmbuild
    - ls -lhrt /rpmbuild
    - docker run  --name=$deploy_container  --volumes-from $gitlab_container -v "/rpmbuild:/rpmbuild:rw"  -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-centos8
    - echo "*************>>  Done - back from inner container"
    - rm -rf /rpmbuild/*
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - docker stop $deploy_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - 158.39.75.5 
  allow_failure: true
  
  
deploy_staging_deb9:
  stage: deploy_and_test
  image: docker:stable
  script:
    - pwd
    - ls 
    - ls /builds
    - mkdir /build
    - echo $CI_PROJECT_DIR
    - cp  $CI_PROJECT_DIR/*.deb /build
    - name_container=deb9_`date +%Y%m%dT%H%M`
    - docker pull maikenp/arc-deploy-debian9
    - gitlab_container=$(docker ps  | awk 'FNR==2' | awk '{print $NF}')
    - docker run --name=$name_container  --volumes-from $gitlab_container  -v "/build:/build" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-debian9 
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - docker stop $name_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - 158.37.63.83
    - deploy
  allow_failure: true
  
  
deploy_staging_deb10:
  stage: deploy_and_test
  image: docker:stable
  script:
    - pwd
    - ls 
    - ls /builds
    - mkdir /build
    - echo $CI_PROJECT_DIR
    - cp  $CI_PROJECT_DIR/*.deb /build
    - name_container=deb10_`date +%Y%m%dT%H%M`
    - docker pull maikenp/arc-deploy-debian10
    - gitlab_container=$(docker ps  | awk 'FNR==2' | awk '{print $NF}')
    - docker run --name=$name_container  --volumes-from $gitlab_container -v "/build:/build" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-debian10
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - docker stop $name_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
  tags:
    - 158.37.63.83
    - deploy
  allow_failure: true

