## Please do not change this file. 
## Doing so will unfortunately create unnesseccary merge conflicts between branches and the fork, and nordugrid/arc version of this file. 
## To have the automatic builds work on your fork, check that the runner is enabled in your fork: Settings->CI/CD->Runner settings

stages:
  - build
  - debs
  - rpms
  - deploy_and_test
  
build_forks_el6:
  stage: build
  image: maikenp/arc-build-centos6
  script: 
  - yum update -y
  - ./autogen.sh
  - ./configure
  - yum-builddep nordugrid-arc.spec -y
  - echo "Run make"
  - make
  - echo "Run make check"
  - make check
  tags:
    - general-shared 
  except: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  allow_failure: false
  
build_forks_deb9:
  stage: build
  image: maikenp/arc-build-debian9
  script: 
  - apt-get update -y
  - ./autogen.sh
  - ./configure
  - apt build-dep nordugrid-arc -y
  - echo "6.0.0">VERSION
  - cp $CI_PROJECT_DIR/debian/changelog.deb $CI_PROJECT_DIR/debian/changelog
  - sed -i 's/trunk-1/6.0.0-1/g' $CI_PROJECT_DIR/debian/changelog
  - dpkg-buildpackage -b -us -uc
  - echo "Run make"
  - make
  - echo "Run make check"
  - make check
  tags:
    - general-shared 
  except: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  allow_failure: false
  

make_debs_deb9:
  stage: debs
  image: maikenp/arc-build-debian9
  script: 
  - apt-get update -y
  - ./autogen.sh
  - ./configure
  - apt-get build-dep nordugrid-arc -y
  - echo "Preparing and running dpkg-buildpackage"
  - cp $CI_PROJECT_DIR/debian/changelog.deb $CI_PROJECT_DIR/debian/changelog
  - echo "6.0.0">VERSION
  - sed -i 's/trunk-1/6.0.0-1/g' $CI_PROJECT_DIR/debian/changelog
  - dpkg-buildpackage -b -us -uc
  tags:
    - general-shared
  only: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
    - ../$CI_PROJECT_DIR
  allow_failure: true
  

make_rpms_el6:
  stage: rpms
  image: maikenp/arc-build-centos6
  script: 
  - yum update -y
  - ./autogen.sh
  - ./configure
  - yum-builddep nordugrid-arc.spec -y
  - echo "Preparing and running rpmbuild"
  - mkdir -p $CI_PROJECT_DIR/rpmbuild/{SOURCES,BUILD,RPMS,SRPMS}
  - echo "%_topdir $CI_PROJECT_DIR/rpmbuild" > ~/.rpmmacros
  - export VERSION=`cat VERSION`
  - make dist
  - cp "nordugrid-arc-${VERSION}.tar.gz" $CI_PROJECT_DIR/rpmbuild/SOURCES
  - rpmbuild -D "_topdir $CI_PROJECT_DIR/rpmbuild" -ba nordugrid-arc.spec
  - cd $CI_PROJECT_DIR
  tags:
    - general-shared 
  only: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
    - $CI_PROJECT_DIR/rpmbuild/SRPMS/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/noarch/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/x86_64/
  allow_failure: false
  
  
make_rpms_el7:
  stage: rpms
  image: maikenp/arc-build-centos7
  script: 
  - yum update -y
  - ./autogen.sh
  - ./configure
  - yum-builddep nordugrid-arc.spec -y
  - echo "Preparing and running rpmbuild"
  - mkdir -p $CI_PROJECT_DIR/rpmbuild/{SOURCES,BUILD,RPMS,SRPMS}
  - echo "%_topdir $CI_PROJECT_DIR/rpmbuild" > ~/.rpmmacros
  - export VERSION=`cat VERSION`
  - make dist
  - cp "nordugrid-arc-${VERSION}.tar.gz" $CI_PROJECT_DIR/rpmbuild/SOURCES
  - rpmbuild -D "_topdir $CI_PROJECT_DIR/rpmbuild" -ba nordugrid-arc.spec
  - cd $CI_PROJECT_DIR
  tags:
    - general-shared
  only: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
    - $CI_PROJECT_DIR/rpmbuild/SRPMS/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/noarch/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/x86_64/
  allow_failure: false
  

 
deploy_staging_el6:
  stage: deploy_and_test
  image: maikenp/arc-deploy-centos6
  script:
    - uname -a
    - echo "Deploying to staging server"
    - yum install -y time
    - echo "Preparing rpms for localinstall"
    - mkdir allrpms
    - cp rpmbuild/RPMS/noarch/* allrpms
    - cp rpmbuild/RPMS/x86_64/* allrpms
    - cd allrpms
    - echo "Doing localinstall"
    - yum localinstall *.rpm -y
     - echo "Installing CAs"
    - wget http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo
    - mv EGI-trustanchors.repo /etc/yum.repos.d/
    - yum install ca_policy_igtf-classic ca_policy_igtf-misc ca_policy_igtf-slcs -y
    - echo "Generating test host certificate"
    - wget http://svn.nordugrid.org/trac/nordugrid/export/32500/contrib/certificate_generator/CertificateGenerator.py
    - python CertificateGenerator.py --CA autocertif --host 158.39.75.5 --validity 365
    - pwd
    - ls -lhrt
    - mv host* /etc/grid-security/
    - mv autocertif* /etc/grid-security/certificates
    - mv *.0 /etc/grid-security/certificates
    - ls -lhrt /etc/grid-security/
    - ls -lhrt /etc/rc.d/init.d
    - ls -lhrt /etc/arc.conf
    - sestatus
    - echo "Preparing folders for arc logs"
    - mkdir $CI_PROJECT_DIR/arc-logs $CI_PROJECT_DIR/arc-tests
    - echo "validating arc.config and starting services"
    - /etc/rc.d/init.d/a-rex validate
    - /etc/rc.d/init.d/a-rex start
    #- /etc/rc.d/init.d/gridftpd start
    - echo 'Test-submit through local plugin '
    - arcproxy -C /etc/.globus/usercert.pem -K /etc/.globus/userkey.pem
    - arcsub -d 5 --direct -c 158.39.75.5 -S org.nordugrid.local /arc/arc-testing/hello.xrls
    - arcsub -d 5 --direct -c 158.39.75.5 -S org.nordugrid.local /arc/arc-testing/hello_inputfile.xrls
    - arcstat --all --long
    #arcinfo sometimes fails, dont know why
    #- arcinfo -c 158.39.75.5 -S org.nordugrid.local
    - echo "Skipping emies submission - not working yet."
    #- echo 'test-submit through emies plugin'
    #- arcsub -d 5 --direct -c 158.39.75.5 -S org.ogf.glue.emies.activitycreation /arc/arc-testing/hello.xrls
    #- arcsub -d 5 --direct -c 158.39.75.5 -S org.ogf.glue.emies.activitycreation /arc/arc-testing/hello_inputfile.xrls
    #- sleep 5m
    - /etc/rc.d/init.d/a-rex stop
    #- /etc/rc.d/init.d/gridftpd stop
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     - $CI_PROJECT_DIR/arc-tests/
  dependencies:
    - make_rpms_el6
  tags:
    - deploy
    - rhel
  only: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  allow_failure: true
 

deploy_staging_el7:
  stage: deploy_and_test
  image: maikenp/arc-deploy-centos7
  script:
    - uname -a
    - echo "Deploying to staging server"
    - yum install -y time
    - echo "Preparing rpms for localinstall"
    - mkdir allrpms
    - cp rpmbuild/RPMS/noarch/* allrpms
    - cp rpmbuild/RPMS/x86_64/* allrpms
    - cd allrpms
    - echo "Doing localinstall"
    - yum localinstall *.rpm -y
     - echo "Installing CAs"
    - wget http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo
    - mv EGI-trustanchors.repo /etc/yum.repos.d/
    - yum install ca_policy_igtf-classic ca_policy_igtf-misc ca_policy_igtf-slcs -y
    - echo "Generating test host certificate"
    - wget http://svn.nordugrid.org/trac/nordugrid/export/32500/contrib/certificate_generator/CertificateGenerator.py
    - python CertificateGenerator.py --CA autocertif --host 158.39.75.5 --validity 365
    - pwd
    - ls -lhrt
    - mv host* /etc/grid-security/
    - mv autocertif* /etc/grid-security/certificates
    - mv *.0 /etc/grid-security/certificates
    - ls -lhrt /etc/grid-security/
    - ls -lhrt /etc/rc.d/init.d
    - ls -lhrt /etc/arc.conf
    - sestatus
    - echo "Preparing folders for arc logs"
    - mkdir $CI_PROJECT_DIR/arc-logs $CI_PROJECT_DIR/arc-tests
    - echo "validating arc.config and starting services"
    - /etc/rc.d/init.d/a-rex validate
    - /etc/rc.d/init.d/a-rex start
    #- /etc/rc.d/init.d/gridftpd start
    - echo 'Test-submit through local plugin '
    - arcproxy -C /etc/.globus/usercert.pem -K /etc/.globus/userkey.pem
    - arcsub -d 5 --direct -c 158.39.75.5 -S org.nordugrid.local /arc/arc-testing/hello.xrls
    - arcsub -d 5 --direct -c 158.39.75.5 -S org.nordugrid.local /arc/arc-testing/hello_inputfile.xrls
    - arcstat --all --long
    # arcinfo sometimes fails, not sure why
    #- arcinfo -c 158.39.75.5 -S org.nordugrid.local
    - echo "Skipping emies submission - not working yet."
    #- echo 'test-submit through emies plugin'
    #- arcsub -d 5 --direct -c 158.39.75.5 -S org.ogf.glue.emies.activitycreation /arc/arc-testing/hello.xrls
    #- arcsub -d 5 --direct -c 158.39.75.5 -S org.ogf.glue.emies.activitycreation /arc/arc-testing/hello_inputfile.xrls
    #- sleep 5m
    - /etc/rc.d/init.d/a-rex stop
    #- /etc/rc.d/init.d/gridftpd stop   
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     - $CI_PROJECT_DIR/arc-tests/
  dependencies:
    - make_rpms_el7
  tags:
    - deploy
    - rhel
  only: 
    - branches@nordugrid/arc
    - tags@nordugrid/arc
  allow_failure: true

##note-to-self: can also downlaod the rpms from latest job with wget 'https://source.coderefinery.org/nordugrid/arc/-/jobs/artifacts/master/download?job=make_rpms' -O artifacts.zip
