#test timestamp
stages:
  - packages
  - deploy_and_test

packages_el8:
  stage: packages
  image: maikenp/arc-build-centos8
  script:
    - echo "$(date +%Y%m%d%H%M%S)" > VERSION
    - yum update -y
    - ./autogen.sh
    - ./configure
    - echo "Preparing and running rpmbuild"
    - mkdir -p rpmbuild/{SOURCES,BUILD,RPMS,SRPMS}
    - make dist
    - VERSION=`cat VERSION`
    - mv nordugrid-arc-${VERSION}.tar.gz rpmbuild/SOURCES
    - rpmbuild -D "_topdir $CI_PROJECT_DIR/rpmbuild" -ba nordugrid-arc.spec
     - rm -f ../*-dbgsym_*.deb
  tags:
    - build
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
    - $CI_PROJECT_DIR/rpmbuild/SRPMS/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/noarch/
    - $CI_PROJECT_DIR/rpmbuild/RPMS/x86_64/
  allow_failure: false


deploy_staging_el8:
  stage: deploy_and_test
  image: docker:stable
  script:
    - pwd
    - echo $CI_PROJECT_DIR
    - ls -lhrt
    - ls -lhrt $CI_PROJECT_DIR/rpmbuild/*
    - export DOCKER_API_VERSION=1.19
    - deploy_container=el8_`date +%Y%m%dT%H%M`
    - docker pull maikenp/arc-deploy-centos7
    - gitlab_container=$(docker ps  | awk 'FNR==2' | awk '{print $NF}')
    - cp -r $CI_PROJECT_DIR/rpmbuild/* /rpmbuild
    - ls -lhrt /rpmbuild
    - docker run  --name=$deploy_container  --volumes-from $gitlab_container --privileged -v "/rpmbuild:/rpmbuild:rw"  -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9002 --publish 9000-9002/udp --rm  maikenp/arc-deploy-centos8
    - echo "*************>>  Done - back from inner container"
    - rm -rf /rpmbuild/*
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
    - docker stop $deploy_container || true
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  dependencies:
    - packages_el8
  tags:
    - 158.39.75.5 
  allow_failure: true
  
  
