## Please do not change this file.
## Doing so will unfortunately create unnesseccary merge conflicts between branches and the fork, and nordugrid/arc version of this file.
## To have the automatic builds work on your fork, check that the runner is enabled in your fork: Settings->CI/CD->Runner settings

stages:
  - build
  - deploy_and_test

fork_packages_el6:
  stage: build
  image: maikenp/arc-build-centos6
  script:
    - echo "$(date +%Y%m%dT%H%M%S)_${CI_COMMIT_SHA:0:8}_master" > VERSION
    - yum update -y
  tags:
      - build
  except:
    refs:
      - master
      - next-major
      - dev-ARC6
      - branches@nordugrid/arc
      - tags@nordugrid/arc
  allow_failure: false


fork_packages_el7:
  stage: build
  image: maikenp/arc-build-centos7
  script:
    - echo "$(date +%Y%m%dT%H%M%S)_${CI_COMMIT_SHA:0:8}_master" > VERSION
    - yum update -y
  allow_failure: false
  tags:
      - build
  except:
    refs:
      - master
      - next
      - branches@nordugrid/arc
      - tags@nordugrid/arc
  allow_failure: false


fork_packages_deb9:
  stage: build
  image: maikenp/arc-build-debian9
  script:
    - apt-get update -y
    - echo "6.0.0" > VERSION
  tags:
      - build
  except:
    refs:
      - master
      - next
      - branches@nordugrid/arc
      - tags@nordugrid/arc
  allow_failure: false


deploy_staging_deb9:
  stage: deploy_and_test
  image: docker:stable
  script:
    - docker run --privileged -v "/arc-testfiles:/arc-testfiles:rw" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9100 --publish 9000-9100/udp --rm  maikenp/arc-deploy-debian9
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - docker-socket-runner1
  allow_failure: true


deploy_staging_el6:
  stage: deploy_and_test
  image: docker:stable
  script:
    - ls -lhrt /arc-testfiles
    - ls -lhrt /arc-logs
    - docker run -v "/arc-testfiles:/arc-testfiles:rw" -v "/arc-testlogs:/arc-testlogs:rw" -v "/arc-logs:/arc-logs:rw" --publish  443  --publish 2811 --publish 9000-9100 --publish 9000-9100/udp --rm  maikenp/arc-deploy-centos6
    - echo "*************>>  Done - back from inner container"
    - ls -lhrt /arc-logs
    - cp -r /arc-logs $CI_PROJECT_DIR
    - ls -lhrt $CI_PROJECT_DIR/arc-logs
    - rm -rf /arc-logs/*
    - ls -lhrt /arc-logs
    - rm -f /arc-testlogs/*
    - ls -lhrt /arc-testlogs
  environment:
    name: staging
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/arc-logs/
     #- $CI_PROJECT_DIR/arc-tests/
  tags:
    - deploy
  allow_failure: true




## note-to-self: can also download the rpms from latest job with (example for el7):
    ## wget 'https://source.coderefinery.org/nordugrid/arc/-/jobs/artifacts/master/download?job=packages_el7' -O artifacts.zip
